backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "page"
    label: "UpwardBound page"
    file: "upward-bound\src\text\sitetext.json"

    # "upward-bound\\src\\text\\sitetext.json"
    create: false
    fields:
      - {name: "home", label: "Home", widget: "string"}
      - {name: "about", label: "About", widget: "string"}
      - {name: "benefits", label: "Benefits", widget: "string"}
      - {name: "development", label: "Development", widget: "string"}
    


